Fix some building problems - build.ps1: problem with build in international system environment - Microsoft.Test.E2E.AspNetCore3x.OData.csproj - missing PackageReference added (see build errors below)      4>C:\ProjectsG\Attis\Labs\OData\Github\WebApi\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\QueryComposition\ServerTypeTests.cs(89,25): error CS1069: The type name 'EventLog' could not be found in the namespace 'System.Diagnostics'. This type has been forwarded to assembly 'System.Diagnostics.EventLog, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [C:\ProjectsG\Attis\Labs\OData\Github\WebApi\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\Build.AspNetCore3x\Microsoft.Test.E2E.AspNetCore3x.OData.csproj]      4>C:\ProjectsG\Attis\Labs\OData\Github\WebApi\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\QueryComposition\ServerTypeTests.cs(89,47): error CS1069: The type name 'EventLog' could not be found in the namespace 'System.Diagnostics'. This type has been forwarded to assembly 'System.Diagnostics.EventLog, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. [C:\ProjectsG\Attis\Labs\OData\Github\WebApi\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\Build.AspNetCore3x\Microsoft.Test.E2E.AspNetCore3x.OData.csproj]      4>C:\ProjectsG\Attis\Labs\OData\Github\WebApi\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\QueryComposition\ServerTypeTests.cs(93,29): error CS0103: The name 'EventLogEntryType' does not exist in the current context [C:\ProjectsG\Attis\Labs\OData\Github\WebApi\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\Build.AspNetCore3x\Microsoft.Test.E2E.AspNetCore3x.OData.csproj]      4>C:\ProjectsG\Attis\Labs\OData\Github\WebApi\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\QueryComposition\ServerTypeTests.cs(115,61): error CS0103: The name 'EventLogEntryType' does not exist in the current context [C:\ProjectsG\Attis\Labs\OData\Github\WebApi\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\Build.AspNetCore3x\Microsoft.Test.E2E.AspNetCore3x.OData.csproj]      4>Done Building Project "C:\ProjectsG\Attis\Labs\OData\Github\WebApi\test\E2ETest\Microsoft.Test.E2E.AspNet.OData\Build.AspNetCore3x\Microsoft.Test.E2E.AspNetCore3x.OData.csproj" (default targets) -- FAILED.